apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "bivac.fullname" . }}-bivac
  labels:
    app: {{ template "bivac.name" . }}-bivac
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "bivac.name" . }}-bivac
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "bivac.fullname" . }}-bivac
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bivac
            - manager
          ports:
            - name: api
              containerPort: 8182
          env:
{{ range .Values.bivac.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
          livenessProbe:
            tcpSocket:
              port: api
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: api
{{ toYaml .Values.probes.readiness | indent 12 }}
          volumeMounts:
            - name: bivac-providers-conf
              mountPath: /etc/bivac
      volumes:
        - name: bivac-providers-conf
          configMap:
            name: {{ template "bivac.fullname" . }}-bivac
