image:
  repository: camptocamp/bivac
  tag: 2.1-dev
  pullPolicy: Always

bivac:
  env:
    - name: BIVAC_ORCHESTRATOR
      value: kubernetes
    - name: KUBERNETES_ALL_NAMESPACES
      value: 'true'
    - name: AWS_ACCESS_KEY_ID
      value: 'XXXXXXXXXXXXXXXXXXXX'
    - name: RESTIC_FORGET_ARGS
      value: 'XXXXXXXXXXXXXX'
    - name: BIVAC_TARGET_URL
      value: 'XXXXXXXXXXXXXXXXXXX'
    - name: AWS_SECRET_ACCESS_KEY
      value: 'XXXXXXXXXXXXXXXXXXX'
    - name: RESTIC_PASSWORD
      value: 'XXXXXXXXXXX'
    - name: BIVAC_SERVER_PSK
      value: 'XXXXXXXXXXXXXXXXXXX'

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    bivac:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    bivac:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
